### ISSUE TITLE
Duplicate Edges on Alignment Import

### ISSUE THREAD

**Issue by wlongabaugh** [RishiDesai/BioFabric#11]
When doing an alignment of yeast 2K-reduced to SC, the system reports 82,150 duplicate links dropped. There are no duplicate links in the original input files. If some are being generated as part of the analysis, and are an artifact, they should be filtered out automatically without bugging the user.

**Comment by RishiDesai** [comment]
Found and fixed a bug in NetAlign processing where links were created twice- and then later thrown out (hence the dialog).
