### ISSUE TITLE
Long Delay on Progress Bar

### ISSUE THREAD

**Issue by wlongabaugh** [RishiDesai/BioFabric#12]
On alignment import, the progress bar stalls for a very long time on 100% progress.mergingLinks (see attached). This implies that some long process following it is not being monitored for progress.

<img width="1393" alt="long100percentmerge" src="https://user-images.githubusercontent.com/8441547/36648156-67f17d04-1a44-11e8-9ed9-2981d6ffe166.png">

**Comment by RishiDesai** [comment]
This is (likely) due to sorting both of the edge sets: O(eloge) time. But no loop reporter can be inserted because the standard library's sort function is being used.

**Comment by wjrl** [comment]
You should split the list into e.g. four sublists and merge them in a loop. Java docs says this will be efficient. We have to have a working progress bar, as this is am interactive program.

**Comment by RishiDesai** [comment]
Now I build a TreeSet with a loop reporter. I do not use a reporter when I added the set's nodes into the list (Collection.addAll) but that shouldn't be a problem.
