### ISSUE TITLE
progress.separatingLinks Progress is Pretty Slow

### ISSUE THREAD

**Issue by wlongabaugh** [RishiDesai/BioFabric#13]
Line 314 of NetworkAlignment seems to be creating a new TreeSet of O(nodes) with each link it processes:

SortedSet<NID.WithName> alignedNodesG2 = new TreeSet<NID.WithName>(largeToMergedID_.values());

TreeSet creation is probably O(nodes*log(nodes)) complexity. Should be able to speed this up with judicious creation of alignedNodesG2.

**Comment by RishiDesai** [comment]
Fixed error where alignedNodesG2 created repeatedly and also assigned variables to binary search operation. Very large speed improvement.
