### ISSUE TITLE
Orphan Edge Net Align Score Dialog

### ISSUE THREAD

**Issue by RishiDesai** [RishiDesai/BioFabric#2]
When Net Align score dialog is opened in Net Align Orphan Edge layout, a null pointer exception comes.

**Comment by wlongabaugh** [comment]
Saw this again a couple of days ago, forgot that I had not captured the stack trace the first time around and neglected to record it. Will be on the lookout for this.

**Comment by wlongabaugh** [comment]
This actually occurred with the edge group layout:

<img width="1398" alt="netalignscoresdump" src="https://user-images.githubusercontent.com/8441547/37572769-385cdfe0-2acd-11e8-8586-d1a1e574f400.png">

**Comment by wlongabaugh** [comment]
Note that if there are no scores, the menu item needs to be disabled. This is specified 
 in the NetAlignScoresAction checkGuts() call, which evaluates true/false if the menu item is enabled or not.

**Comment by RishiDesai** [comment]
There are always be measures for all three commands (Edge, Orphan, CaseII Cycle). Topological measures are always calculable, so dialog is active for all three commands.
