### ISSUE TITLE
Loop Reporter for NetAlign Node order

### ISSUE THREAD

**Issue by RishiDesai** [RishiDesai/BioFabric#28]
The loop reporter is messed up when calculating NetAlign node ordering.

**Comment by wjrl** [comment]
This line is still in NetworkAlignmentLayout: UiUtil.fixMePrintout("Loop Reporter all messed up in NetworkAlignmentLayout.FlushQueue");

**Comment by RishiDesai** [comment]
removed the statement in a1afa84b980ce0ab9d7e2aa2d5434a4ec9709443. Issue still needs to be fixed...

**Comment by wjrl** [comment]
Hoisted the LoopReporter creation out of flushQueue, updated based on full count of target nodes. The change has been merged to AlignmentPlugin master.

**Comment by wjrl** [comment]
The issue can be closed.
