### ISSUE TITLE
File chooser Net Align Dialog

### ISSUE THREAD

**Issue by RishiDesai** [RishiDesai/BioFabric#3]
file chooser shows up under Net Align Dialog. Need to use 'topWindow_' as argument.

**Comment by wjrl** [comment]
This is on Mac OSX 10.12.6, Java 8 Update 144, right after clicking on the Graph2 button (feb4.jar). Also seen on 10.10.5:
<img width="628" alt="filechooserunderalignment" src="https://user-images.githubusercontent.com/4065595/36364830-4ecb7562-14fb-11e8-9277-d938a2bb56ed.png">

**Comment by RishiDesai** [comment]
I now use "selectionWindow" instead of "mainWindow". Does this fix the bug? (can't test on my mac)

**Comment by wjrl** [comment]
We are still having this problem on High Sierra, but not on Yosemite. This is really annoying.

**Comment by wjrl** [comment]
Or maybe it is the Java version that is bundled with the BioFabric app. Still digging.

**Comment by wjrl** [comment]
With a fresh build through my executable-generating release pipeline, it is now working on High Sierra. Close this issue.
