### ISSUE TITLE
Incorrect Handling of an IOException

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#37]
GWImportLoader.isGWFile(File file) currently catches IOExceptions and displays them in the Exception Handler. IOExceptions (e.g. FileNotFound) are a common occurrence and should not be displayed as a stack trace to the user.

**Comment by RishiDesai** [comment]
fixed with 20ac2cd939158904db30c7da1c135e0fc35c7b70 . Now IOE returns 'false', just like when a NumberFormatException is thrown. If the file is gibberish, it will assume to be sif-> then IOE will be formally dealt with in SIF loader after it is thrown.
