### ISSUE TITLE
Measures diactivated with Bif

### ISSUE THREAD

**Issue by RishiDesai** [RishiDesai/BioFabric#38]
When reading bif files, measure action is greyed out. Measures are properly written and read to in bifs.

**Comment by wjrl** [comment]
Note that I changed the code to make sure that measures were being dropped if a new network was being imported. Previously, the measures were retained even with a newly loaded network that was not an alignment. This issue might be related.

**Comment by RishiDesai** [comment]
Fixed the issue with BIF, but the old issue returned. If The newly imported network, whether a BIF (w/ no previous networks already loaded) or a SIF/GW (with a Net align already loaded), do not have any 'pending' measures- thus the Measures action is activated. But deactivating it if there is no pending will deactivate both netalign BIFs and SIF/GW. There is no way to distinguish the two.

**Comment by RishiDesai** [comment]
This should be fully fixed with https://github.com/RishiDesai/AlignmentPlugin/commit/f41a8f773377a0dc20f35833975908eb13cec6eb
