### ISSUE TITLE
After loading gw file for alignment, the "Specify Directional Relationships" dialog is blank

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#6]
Although a .gw file has no link tag, something should be filled in (e.g. "default", "noRel"?) so that the "Specify Directional Relationships" dialog has something to show ans pick:

<img width="1391" alt="norel" src="https://user-images.githubusercontent.com/4065595/36365570-0117d078-14ff-11e8-924b-64e44dffed2d.png">

**Comment by wlongabaugh** [comment]
Currently having problems reproducing this error.

**Comment by wlongabaugh** [comment]
This error occurs if the user accidentally enters the same network for files 1 and 2. (Same inputs as Issue #7 : yeast0.gw both times)

**Comment by wlongabaugh** [comment]
Note that there is no stack trace at this point. Stack trace comes after hitting OK button.

**Comment by RishiDesai** [comment]
This happened when user entered same file and then perfect alignment on orphan edge layout, resulting in an empty network. This is now fixed with a dialog that says it is an empty network.
