### ISSUE TITLE
Stack Trace on Orphan Edge Layout Load

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#7]
After loading the reduced yeast network, SC network, and alignment file for the Orphan Edge Layout, and after clicking OK on the Directionality dialog, I get this stack dump (Feb4 jar):

<img width="1398" alt="orphanlayoutstackdump" src="https://user-images.githubusercontent.com/4065595/36365688-7903e98c-14ff-11e8-9cf0-18e551433bc4.png">

**Comment by wlongabaugh** [comment]
Currently having problems reproducing this error.

**Comment by wlongabaugh** [comment]
This error occurs if the user accidentally enters the same network for files 1 and 2. (Same inputs as Issue #6 : yeast0.gw both times)

**Comment by RishiDesai** [comment]
Same error as #6
