### ISSUE TITLE
Incorrect First Node Zone Label, Nav

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#8]
Per the attached screen shot, the first node zone is incorrectly labeled with a duplicate name of the second zone, and the nav bar shows "Mouse Over Node Link Zone: \<none\>" while mouse cursor (simulated here with a drawn arrow) is over the zone. Should be reading "SWD2".

<img width="1395" alt="badnodezone" src="https://user-images.githubusercontent.com/4065595/36406285-94c907fa-15aa-11e8-925d-614999579e3e.png">

**Comment by wlongabaugh** [comment]
This only shows up when shadow links are enabled.
