### ISSUE TITLE
Orphan Edge Layout Feature Requests

### ISSUE THREAD

**Issue by wjrl** [RishiDesai/BioFabric#9]
To be really useful, I think the Orphan Edge Layout needs to have nodes labeled with their aligned match, and edges labeled as purple or blue. I'm having a hard time at the moment gleaning much from the presentation (my fault for not noticing this sooner).

**Comment by RishiDesai** [comment]
Orphan Layout now uses merged names and links retain their tags (G1A,G12, etc).
